[package]
name = "fmi"
version = "0.2.0"
authors = ["John Hughes <jondo2010@gmail.com>"]
edition = "2018"
exclude = ["data/*"]
description = "A Rust interface to FMUs (Functional Mockup Units) that follow the FMI Standard. See http://www.fmi-standard.org/"
repository = "https://gitlab.com/jondo2010/rust-fmi"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["model", "ode", "modelica"]
categories = ["science", "simulation"]

[badges]
gitlab = { repository = "jondo2010/rust-fmi", branch = "master" }
codecov = { repository = "jondo2010/rust-fmi", branch = "master", service = "gitlab" }

[build-dependencies]
cc = "1.0.61"
built = "0.4.3"

[dependencies]
serde = {version = "1.0.107", features = ["derive"] }
serde-xml-rs = "0.4.0"
dtparse = "1.0.3"
num-traits = "0.2.12"
derive_more = "0.14.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
zip = "0.5.8"
url = "2.1.1"
tempfile = "3.1.0"
chrono = { version = "0.4.6", features = ["serde"] }
libc = { version = "0.2.79", features = ["align"] }
log = { version = "0.4.6", features = ["std", "serde"] }
thiserror = "1.0.21"

[dev-dependencies]
quicli = "0.4.0"
structopt = "0.2"
prettytable-rs = "0.8.0"
pretty_env_logger = "0.4.0"
interpolation = "0.1.0"
csv = "1.0.5"
assert_approx_eq = "1.1.0"
#anyhow = "1.0.33"
