[package]
name = "fmi"
version = "0.2.1"
authors = ["John Hughes <jondo2010@gmail.com>"]
edition = "2021"
include = [
    "/Cargo.toml",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md",
    "/build.rs",
    "/examples/**",
    "/src/**",
]
description = "A Rust interface to FMUs (Functional Mockup Units) that follow the FMI Standard. See http://www.fmi-standard.org/"
repository = "https://gitlab.com/jondo2010/rust-fmi"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["model", "ode", "modelica"]
categories = ["science", "simulation"]

[badges]
gitlab = { repository = "jondo2010/rust-fmi", branch = "master" }
codecov = { repository = "jondo2010/rust-fmi", branch = "master", service = "gitlab" }

[build-dependencies]
cc = "1.0"
built = "0.6"

[dependencies]
serde = {version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
dtparse = "1.0"
num-traits = "0.2"
derive_more = "0.99"
dlopen = "0.1"
dlopen_derive = "0.1"
zip = "0.6"
url = "2.2"
tempfile = "3.1"
chrono = { version = "0.4", features = ["serde"] }
libc = { version = "0.2", features = ["align"] }
log = { version = "0.4", features = ["std", "serde"] }
thiserror = "1.0"

[dev-dependencies]
pretty_env_logger = "0.4"
csv = "1.0"
assert_approx_eq = "1.1"

[workspace]
members = ["fmi_check"]