name: Rust
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
      - uses: actions/checkout@v4

      - uses: swatinem/rust-cache@v2

      - name: fetch Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      
      - name: toolchain version
        run: cargo -vV

      - name: install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: liblapack3
          version: 1.0

      - name: build
        run: cargo build --verbose

      - name: test
        run: cargo test --verbose